/**
 * render_examples.js — render every route's Slack message with sample data and
 * write examples.md. Run: `node shared/slack-messages/render_examples.js`
 * Output is reference copy + paste-ready Block Kit JSON for the Make.com build.
 */
const fs = require('fs');
const path = require('path');
const { buildMessage } = require('../lib/format');
const { extractFields } = require('../lib/fields');
const { ROUTES } = require('../lib/config');

const sample = {
  id: 10763, firstName: 'Tom', lastName: 'Minch', stage: 'Lead',
  source: 'Spring Absentee PA', assignedTo: 'Reyes Smith', customLeadManager: 'Jane Doe',
  addresses: [{ street: '322 S Broadway', city: 'Los Angeles', state: 'CA', code: '90003' }],
};
const f = extractFields(sample);

let md = '# Slack message examples (rendered with sample data)\n\n';
md += '> Generated by `render_examples.js` from the SOW §5 templates. Bold = single `*asterisks*`, links = `<url|text>`.\n\n';

// One block per distinct template, in route order (dedupe shared templates).
const seen = new Set();
for (const r of ROUTES) {
  if (seen.has(r.template)) continue;
  seen.add(r.template);
  const m = buildMessage(r.template, f);
  md += `## ${r.template}  \n`;
  md += `Used by: ${ROUTES.filter(x => x.template === r.template).map(x => `\`${x.stage}\``).join(', ')}\n\n`;
  md += '**Rendered text (mrkdwn):**\n\n```\n' + m.text + '\n```\n\n';
  md += '**Block Kit `blocks` (paste into Slack module):**\n\n```json\n' + JSON.stringify(m.blocks, null, 2) + '\n```\n\n';
}

// Catch-all
const cm = buildMessage('catchall', { ...f, stage: 'Pending Closer Contact' });
md += '## catchall (no closer assigned)\n\n';
md += '**Rendered text:**\n\n```\n' + cm.text + '\n```\n\n';
md += '**Block Kit:**\n\n```json\n' + JSON.stringify(cm.blocks, null, 2) + '\n```\n';

fs.writeFileSync(path.join(__dirname, 'examples.md'), md);
console.log('Wrote', path.join(__dirname, 'examples.md'));
